spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2
    username: root
    password: 6685765aa
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

  security:
    oauth2:
      client:
        # OAuth 로그인 시 설정한 Application의 정보를 사용하여
        # AccessToken을 Authorization Server에게 발급받을 때 사용
        registration:
          kakao:
            client-id: 9c443fa59dc9ffb91bb4b74991c21de0
            client-secret: 46WP5eyA8DGAClOW1X8Xci7LR7yPmxED
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
          # AccessToken을 Authorization Server에게 발급 받은 후,
          # 해당 AccessToken으로 Resource Server의 API를 사용할 때
          # provider 부분의 정보를 사용하여 API 호출
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  auth:
    token-secret: devbeekei-token-secret-key
    token-expiration-time: 604800000

logging:
  level:
    root: DEBUG